### ISSUE TITLE
تغییرات در شاخه ی اصلی اعمال نمی شود

### ISSUE THREAD

**Issue by sohrabkhanbadr** [mehdisadeghi/jekyll-theme-mehdix-rtl#12]
<div dir='rtl' lang='fa'>
با سلام، بنده بعد از تغییر مقادیر در فایل  config.yml در شاخه ی master همانند  title و آدرس ایمیل و ... « روز نوشت های من» و «من می نویسم پس هستم» یا تغییر فایل ها در بخش post سایت، باز هم مقادیر پیشفرض را در سایت می بینم.به عبارتی تغییرات اعمال نمی شود. آیا می توانید من را راهنمایی نمایید ؟ با تشکر از شما اینجانب سهراب خان بدر
</div>

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
سلام.
من متوجه مشکل نشدم. مفصل شرح بدهید جواب بهتری می‌توانم بدهم..

سایت را بیلد کردید و خروجی همان بود؟
خروجی بیلد چه بود؟
چطور بیلد کردید؟

روش کار اینست که یا فورک بکنید و آنطوری که در صفحه اصلی نوشته‌ام بدهید گیت‌هاب بیلد بکند. یا اینکه کلون بکنید و روی کامپیوتر خودتان بعد از نصب جکیل و وابستگی‌ها بیلد بکنید.

جواب اینها را بدهید تا مشکل را پیدا بکنیم.
</div>

**Comment by sohrabkhanbadr** [comment]
<div dir='rtl' lang='fa'>
سلام. من روش فورک را انتخاب کردم.
 
در ابتدا منبع را فورک کردم
فایل config.yml را با مقادیر دلخواه مقداردهی کردم 
فایل های داخل فولدر posts را کمی تغییر دادم
تنظیمات github page  را در تنظیمات بررسی کردم و در نهایت لینک 
[سایت مورد نظر](https://sohrabkhanbadr.github.io/jekyll-theme-mehdix-rtl/)
را دریافت کردم. تنظیمات را  در تصویر مشاهده می کنید.
![image](https://user-images.githubusercontent.com/65416303/85615217-25cd6980-b671-11ea-9867-81257eee8535.png)

 ممنون. سهراب خان بدر
</div>

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
حدس‌هایی می‌زنم که تست بکنید به نظرم مشکل حل می‌شود.

اول لطفا کنترل بکنید که کلید بیلد ساخته باشید. برای استفاده از اکشن بیلدی که من موقع نوشتن «ریدمی» استفاده کرده‌ام ساخت یک کلید ضروری است. شرح بیشتر [اینجا](https://github.com/mehdisadeghi/jekyll-theme-mehdix-rtl#%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A8%D9%87-%D8%B1%D9%88%D8%B4-%D9%81%D9%88%D8%B1%DA%A9).

> بدون هیچ تغییر دیگری همینکه تغییرات خودتان را پوش کنید سایت بیلد می‌شود اما در gp-pages کپی نمی‌شود. علت هم نقص در گیت‌هاب است چون امکان بیلد را ماکروسافت اخیرا بعد از خریداری گیت‌هاب اضافه کرده است و هنوز در حال تکمیل است. راه حلی که پیدا کردم استفاده از یک کلید جداگانه برای بیلد است. برای اینکار باید یک کلید روی کامپیوترتان بسازید و به تنظیمات ریپازیتوری گیت‌هابتان اضافه کنید.

دوم اگر نگاه بکنید [تب بیلد](https://github.com/sohrabkhanbadr/jekyll-theme-mehdix-rtl/actions) ریپازیتوری شما خالی است. یعنی هیچ چیزی بیلد نشده است و شما دارید همان [بیلدهای کهنه](https://github.com/sohrabkhanbadr/jekyll-theme-mehdix-rtl/actions) سایت من را می‌بینید.

دست آخر هم اطمینان حاصل کنید که در تنظیمات گیت‌هاب بیلد فعال است:

![image](https://user-images.githubusercontent.com/3101557/85627487-dede7480-b66e-11ea-80e1-4a783c771f62.png)

لطفا اینها را امتحان کنید و خبر بدهید.

</div>

**Comment by sohrabkhanbadr** [comment]
<div dir='rtl' lang='fa'>
سلام، مهدی عزیز، بسیار خوشحالم، فرایند بیلد موفق آمیز بود. ممنون.

</div>
