### ISSUE TITLE
با تغییر نام ریپوزیتوری قالب از کار می افتد 

### ISSUE THREAD

**Issue by sohrabkhanbadr** [mehdisadeghi/jekyll-theme-mehdix-rtl#13]
<div dir='rtl' lang='fa'>
سلام، با تغییر نام ریپوزیتوری سایت به شکل زیر نمایش داده می شود.

[آدرس سایت](https://sohrabkhanbadr.github.io/music-auto-tagging/)

![image](https://user-images.githubusercontent.com/65416303/85967264-4f6ef380-b9d7-11ea-836f-37f41b9bf77c.png)

</div>

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
سلام. متوجه مشکل نشدم. سایت را دیدم که ظاهرا درست است. تصویری که شما ضمیمه کرده‌اید خبر از لود نشدن استایل‌شیت‌ها می‌دهد که یعنی آدرس جایی غلط است. اگر کلید اف ۱۲ را بزنید یا دولوپر کنسول فایرفاکس یا کروم را باز کنید آدرس‌های خطا را خواهید دید.
باز هم بیشتر توضیح بدهید تا بتوانم کمک کنم.
</div>

**Comment by sohrabkhanbadr** [comment]
<div dir='rtl' lang='fa'>
سلام . ممنون از شما مشکل من حل شده است. شاد و پیروز باشید.
</dive

**Comment by sohrabkhanbadr** [comment]
<div dir='rtl' lang='fa'>
سلام. من وقتی پستی را بارگذاری می کنم. صفحه ی اصلی بروز می شود . آدرسی که در ادامه ی مطلب می آورد را از سایت جکیل می خواند و من با ارور 404 مواجه میشوم. راه حل فعلی که دارم آن است که از روی ریپوزیتوری یک کپی با نام jekyll-theme-mehdix-rtl  ساخته و پست ها را آن جا بارگذاری کنم.
</div>
<div dir='rtl' lang='fa'>
برای مثال به پست جدید من توجه کنید:
این پست از آدرس اصلی سایت یعنی :
[برچسب گذاری خودکار اطلاعات موسیقیایی](https://sohrabkhanbadr.github.io/music-auto-tagging/)
خوانده می شود و  حال بر روی هر پستی که کلیک کنید از آدرس زیر خوانده می شود:
![جکیل-تم-مهدیکس-ار تی ال](https://sohrabkhanbadr.github.io/jekyll-theme-mehdix-rtl/)
</div>

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
دو تا اشکال دیدم مقادیرش رو تغییر بدین درست می‌شه.

[ایراد اول](https://github.com/sohrabkhanbadr/music-auto-tagging/blob/master/_config.yml#L9)
[ایراد دوم](https://github.com/sohrabkhanbadr/music-auto-tagging/blob/master/.github/workflows/gh-pages.yml#L16)

در هر دو مورد مقدار _basedir_ غلطه. 
در همون فایل کانفیگ [مثال](https://github.com/sohrabkhanbadr/music-auto-tagging/blob/master/_config.yml#L10) مقدار صحیحش هست.
</div>

**Comment by sohrabkhanbadr** [comment]
<div dir='rtl' lang='fa'>
سایت به خوبی کار می کند. بار دیگر ممنون از شما.
</div>
