### ISSUE TITLE
systematic way to change the main color theme (pink schema)

### ISSUE THREAD

**Issue by kave-me** [mehdisadeghi/jekyll-theme-mehdix-rtl#7]
is there a predefined way to change the main color schema, by that I mean is it possible to change the theme via changing the value of a variable in the config file?

**Comment by mehdisadeghi** [comment]
You can try modifying the values inside [assets/css/main.scss](https://github.com/mehdisadeghi/jekyll-theme-mehdix-rtl/blob/master/assets/css/main.scss).
