### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by kave-me** [mehdisadeghi/jekyll-theme-mehdix-rtl#8]
I forked your blog, then I just modified CNAME and immediately after that, I received an email from GitHub with the following content:

> The page build failed for the `master` branch with the following error:
> 
> The jekyll-theme-mehdix-rtl theme is not currently supported on GitHub Pages. For more information, see https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

the main Question is that I can't Understand whether the two repositories are identical how it is possible that you are using it without any problem and I cant!

**Comment by mehdisadeghi** [comment]
> The jekyll-theme-mehdix-rtl theme is not currently supported on GitHub Pages. 

True.

Github supports a very limited set of plugins and gems during builds, this theme is not one of them.

> the main Question is that I can't Understand whether the two repositories are identical how it is possible that you are using it without any problem and I cant!

You are using Github pages, I don't.

Please see [this](https://mehdix.ir/tag/%D8%AC%DA%A9%DB%8C%D9%84.html) and [this](https://mehdix.ir/netlify.html).

You should use a custom CI pipeline like Travis, build after each change, and push back to your gh-pages branch. Or serve your site elsewhere, like on Netlify.
